### ISSUE TITLE
use this code with Arduino Mega

### ISSUE THREAD

**Issue by hesan621** [Earsuit/MPU9250-calibration#1]
Hi.i want to use this calibration method with Arduino mega.
I upload this code on Mega2560 , and I received the following error.
 'I2C_FAST_MODE' was not declared in this scope.

**Comment by Earsuit** [comment]
Hi, sorry for the late reply. The code only tested on STM32,  you need to modify the I2C part to get it work on Arduino. However, the code here does nothing but get the raw data from the sensor. It is the MATLAB code that process the data and output the calibration parameters. You could check my blog for more [info](https://xianyu.world/?p=99&lang=en). Hope it's help and feel free to contact me :)

**Comment by hesan621** [comment]
Thanks Earsuit. I solve this problem

**Comment by Earsuit** [comment]
Haha, that's great!
